name: Snyk Infrastructure as Code and GitHub Security example
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #Setup Environment
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    #Configure AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
      # Install OPA
    - name: Install OPA & Build ruleset
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod 755 ./opa
        ./opa build ./custom_rules.rego  -t wasm -e "main/deny"
        ls 
       # Scan Terraform Plan
    - name: Build TF Plan
      run: |
        terraform init
        terraform plan -out tf.plan 
        terraform show -json tf.plan > tf-plan.json
            
    - name: Run Snyk IaC
      id: snyk
      continue-on-error: true
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test tf-plan.json --scan=planned-values --rules=bundle.tar.gz --sarif-file-output=snyk.sarif
     
